"""
Type-directed Hypothesis generators for FPy programs.

Phase 1 scope (deliberately small):
- One target type: ``RealType``.
- One construction shape: a ``FuncDef`` with N real-typed parameters and a
  single ``ReturnStmt`` whose expression has type ``real``.
- Expression language: ``Integer`` literals, parameter ``Var`` references,
  and arithmetic ops ``Add`` / ``Sub`` / ``Mul`` / ``Neg`` / ``Abs``.
  (``Div`` is deferred because division by zero would crash the runtime
  smoke test; ``Decnum`` and transcendentals are deferred to a later phase.)

The architecture is intentionally type-indexed even though only ``RealType``
is supported: every recursive helper takes a target ``Type`` and an
environment of typed bindings, which is the structure later phases will
extend with ``BoolType`` / ``TupleType`` / etc.

Construction is AST-direct (we build ``FuncDef`` nodes and feed them into
the same passes the ``@fp.fpy`` decorator pipeline runs), so the parser is
*not* exercised here — phase-1 targets analyses and the interpreter.
"""

from typing import TypeAlias

from hypothesis import strategies as st

import fpy2 as fp

from fpy2.ast.fpyast import (
    Abs,
    Add,
    Argument,
    Expr,
    FuncDef,
    FuncMeta,
    Integer,
    Mul,
    Neg,
    RealTypeAnn,
    ReturnStmt,
    StmtBlock,
    Sub,
    Var,
)
from fpy2.env import ForeignEnv
from fpy2.types import RealType, Type
from fpy2.utils import NamedId


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

TypeEnv: TypeAlias = dict[NamedId, Type]
"""Mapping from in-scope names to their FPy types."""


# ---------------------------------------------------------------------------
# Phase 1: real-typed expressions
# ---------------------------------------------------------------------------

_LITERAL_RANGE = (-1_000, 1_000)


def _real_literal_strategy() -> st.SearchStrategy[Expr]:
    return st.integers(*_LITERAL_RANGE).map(lambda v: Integer(v, None))


def _real_var_strategy(env: TypeEnv) -> st.SearchStrategy[Expr] | None:
    """Strategy for ``Var`` references to real-typed bindings in ``env``.

    Returns ``None`` if there are no real-typed bindings in scope, so the
    caller can skip emitting this branch entirely.
    """
    real_names = sorted(
        (n for n, t in env.items() if isinstance(t, RealType)),
        key=str,
    )
    if not real_names:
        return None
    return st.sampled_from(real_names).map(lambda n: Var(n, None))


def real_expr(env: TypeEnv, depth: int) -> st.SearchStrategy[Expr]:
    """Strategy for an FPy expression of type ``real`` under ``env``.

    ``depth`` bounds the maximum nesting depth of compound operations; at
    ``depth == 0`` only leaf expressions (literals and variable references)
    are produced.

    Shrinking note: Hypothesis biases toward earlier options in
    ``st.one_of``, so leaves are listed first to favor minimal counterexamples.
    """
    leaves: list[st.SearchStrategy[Expr]] = [_real_literal_strategy()]
    var_strat = _real_var_strategy(env)
    if var_strat is not None:
        leaves.append(var_strat)

    if depth <= 0:
        return st.one_of(*leaves)

    sub = real_expr(env, depth - 1)

    def _binop(cls):
        return st.tuples(sub, sub).map(lambda ab: cls(ab[0], ab[1], None))

    def _unop(cls):
        return sub.map(lambda x: cls(x, None))

    inner: list[st.SearchStrategy[Expr]] = [
        _binop(Add),
        _binop(Sub),
        _binop(Mul),
        _unop(Neg),
        _unop(Abs),
    ]
    return st.one_of(*leaves, *inner)


# ---------------------------------------------------------------------------
# Function definitions
# ---------------------------------------------------------------------------

def _make_arg_names(n: int) -> list[NamedId]:
    return [NamedId(f'x{i}') for i in range(n)]


def _make_funcdef(name: str, arg_names: list[NamedId], body_expr: Expr) -> FuncDef:
    """Wrap an expression in a ``f(arg_names...) -> Real: return body_expr``."""
    args = [Argument(n, RealTypeAnn(None, None), None) for n in arg_names]
    body = StmtBlock([ReturnStmt(body_expr, None)])
    meta = FuncMeta(set(), None, None, {}, ForeignEnv.default())
    return FuncDef(name, args, body, meta)


@st.composite
def fpy_real_funcdef(
    draw,
    num_args: st.SearchStrategy[int] | None = None,
    max_depth: st.SearchStrategy[int] | None = None,
) -> FuncDef:
    """Generate a well-typed FPy function ``f(x0..xN: Real) -> Real``.

    The body is a single ``return <expr>`` where ``<expr>`` is generated by
    :func:`real_expr` with the given depth budget.
    """
    if num_args is None:
        num_args = st.integers(0, 3)
    if max_depth is None:
        max_depth = st.integers(0, 3)

    n = draw(num_args)
    depth = draw(max_depth)

    arg_names = _make_arg_names(n)
    env: TypeEnv = {name: RealType() for name in arg_names}
    body_expr = draw(real_expr(env, depth))
    return _make_funcdef('f', arg_names, body_expr)


def fpy_real_function(
    num_args: st.SearchStrategy[int] | None = None,
    max_depth: st.SearchStrategy[int] | None = None,
) -> st.SearchStrategy[fp.Function]:
    """Same as :func:`fpy_real_funcdef` but wraps the AST in :class:`fp.Function`."""
    return fpy_real_funcdef(num_args=num_args, max_depth=max_depth).map(fp.Function)
