name: Documentation generation

on: [push]

env:
  SPHINXOPTS: "-W"

jobs:
  mypy:
    name: "Generate documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.11"
      - name: Install fpy2
        run: uv sync
      - name: "Create empty directories"
        run: mkdir docs/source/_static
      - name: "Generate documentation"
        run: uv run make html -C docs/
