name: Build and check

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip build
      - name: Build package
        run: python -m build
      - name: Install fpy2
        run: pip install .

  mypy:
    name: "Mypy analyzer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install --upgrade pip mypy
      - name: Install fpy2
        run: pip install .
      - name: Check
        run: mypy fpy2

  ruff:
    name: "Ruff linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install --upgrade pip ruff
      - name: Install fpy2
        run: pip install .
      - name: Lint
        run: ruff check
